### ISSUE TITLE
Class 'Themosis\Foundation\Application' not found

### ISSUE THREAD

**Issue by maruf-cefalo** [themosis/bookstore#12]
I just clone the repo and checkout to v2.0. After getting all the usual installation process I am getting this error, can someone help here please.

**Comment by jlambe** [comment]
This project has not yet been updated to version 2. The branch is in a work-in-progress state. If you want to learn the framework, I suggest you to follow the 4 part tutorial on the blog:
- https://blog.themosis.com/2019/11/21/getting-started-with-the-themosis-framework-part-1/

**Comment by maruf-cefalo** [comment]
Thanks a lot
