### ISSUE TITLE
Can't get the bookstore to work

### ISSUE THREAD

**Issue by bjorntheart** [themosis/bookstore#4]
Hi @jlambe 

I clone the the bookstore repo and did a composer install. I setup my database, went through the WP install screens, but don't know how to setup the bookstore any further. 

I see no Books custom post type and when visiting the front end I get a blank screen.

**Comment by jlambe** [comment]
Yes because no data are available by default.
You need to create a front page and set it on the settings then add miscellaneous books.

The bookstore project is only for code example on how/where to write code.

**Comment by bjorntheart** [comment]
Noted thanks Julien. Would be great to have a fully working example complete with DB, but I do understand that you are the only dev on the project so far and this is would be probably be a low priority item. Wish I knew more of the framework to get something like this up and running. 
Anyhow, I did encounter some problem with the URLs not working on several installs of Themosis and have posted about it here [#156](/themosis/framework/issues/156)

**Comment by jlambe** [comment]
You can also check the "themosis/todo" code, normally it should work without any data.

**Comment by bjorntheart** [comment]
Great! Thanks, I'll be sure to check it out.

**Comment by Malakohvmisha** [comment]
Can you pack a mysql table?

**Comment by jlambe** [comment]
Will look after it but I'll pack an xml file to import only the "books" custom post type. But you'll have to wait because I will update the bookstore project to work seamlessly with release 1.2.0 first.

**Comment by 3KyNoX** [comment]
Hello,

Get it to work if I remove condition : 

if (themosis_is_post($about->ID))

in admin/about.php

I also added a book inside WP-Admin which appear on "Popular" Title on the front page (without book image that have been set), and when clicking on the newly created book, I got the error message : 

No route defined for this request...

Blog part looks like working.

**Comment by jlambe** [comment]
Yeah it's missing content when you install the project. You need to create an "About" page in WordPress.
Same issue as Todo app, I should probably update them with next release and also add the content images and a mysql dump with the project.
