### ISSUE TITLE
Not supported with latest themosis version.

### ISSUE THREAD

**Issue by brijeshborad** [themosis/bookstore#5]
Hello,
I have tried to setup this demo in my localhost to understand the flow of themosis framework but I was getting error "Class not found exception(Route class)". I think this demo has different theme structure than the latest one that's why I was not able to execute this demo.

Have you any other example(with the database if possible) that can be setup with localhost(virtual host in local)? I am really very excited to learn this framework.
Thanks.

**Comment by jlambe** [comment]
Not directly. Currently I would advise you to install a new version and read the code from the bookstore theme as a reference.
This example is in fact compatible with version 1.0 or 1.1 at least but not the latest. We'll update it for next release 1.3.0 which brings a lot of improvements and APIs.
Also you can ask any questions on the Gitter room for help: https://gitter.im/themosis/framework
