### ISSUE TITLE
Class Dev\Bookstore\Books\Models\Books does not exist

### ISSUE THREAD

**Issue by souhailmerroun** [themosis/bookstore#8]
Hello,

After a fresh install of this bookstore theme, a composer install. I configure the .env file and then the first page i see is this exception.

![screenshot from 2017-02-14 02-38-15](https://cloud.githubusercontent.com/assets/8895242/22912686/a7d7e03e-f25e-11e6-8f7d-4c7ff5bce6fd.png)

**Comment by jlambe** [comment]
Hi,
the project is not yet fully refactored but I would say that the `books-manager` plugin coming with it (boostore-books if not latest version) is not activated.

When the bookstore will be refactored, I'll post with it a MySQL dump so you'll be able to install it with dummy data. If you still want to try it out without data, run another `composer  update`, install it and activate the plugin from the admin.

**Comment by souhailmerroun** [comment]
Thanks @jlambe , great work by the way (y)

**Comment by jlambe** [comment]
@souhailmerroun thank you 😃
