### ISSUE TITLE
Missing Class Dev\Bookstore\Books\Models\Books

### ISSUE THREAD

**Issue by wordpressseo6** [themosis/bookstore#9]
Unfortunately the theme is unusable because missing the class Dev\Bookstore\Books\Models\Books

**Comment by jlambe** [comment]
Hi, please check this issue: https://github.com/themosis/bookstore/issues/8

The project is not yet ready for use and do not yet contain the MySQL dump for testing. If you still want to use it in its infancy state, make sure to run a composer update and activate the bundled plugin first.

**Comment by wordpressseo6** [comment]
Hello, thanks for the answer.

I did more: I have created a database, a clean install of the whole framework and virtualhost. I also run composer install all the directories in which I found a composer.json files but unfortunately still does not work.

**Comment by jlambe** [comment]
@wordpressseo6 You should not run a `composer update` in all directories which have a configuration file. Only the project root one. The other files are only used for package naming.
